# Generated by Django 4.0.4 on 2022-04-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_product_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='rate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rate'),
        ),
    ]
